name: capstone_s6
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.4 <3.0.0'

dependencies: 
  sqflite: ^2.2.8+4
  sqflite_common_ffi_web: ^0.3.5+1
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_spinkit: 5.1.0
  get_storage: 2.1.1
  http: 0.13.6
  shared_preferences: 2.1.2
  flutter_otp_text_field: 1.1.1
  image_picker: 0.8.7+4
  line_awesome_flutter: 2.0.0
  flutter_dialogs: 3.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/logo.png
    - assets/images/forgot.png
    - assets/images/auth.png
    - assets/images/pp.png

