name: capstone_s6
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  splashscreen: 1.3.5
  flutter_spinkit: 5.1.0
  get_storage: 2.1.1
  http: 0.13.6
  shared_preferences: 2.1.0
  flutter_otp_text_field: 1.1.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/logo.png
    - assets/images/forgot.png
    - assets/images/auth.png

